import type { Metadata } from "next";
import "./globals.css";
import { Fira_Sans_Condensed } from 'next/font/google'

const firaSansCondensed = Fira_Sans_Condensed({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-fira-sans-condensed',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaSansCondensed.className} antialiased bg-[#000e2f]`}
      >
        {children}
      </body>
    </html>
  );
}
